[package]
name = "rust_clap_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap-sys = "0.3.0"
slint = "1.0.2"

[build-dependencies]
slint-build = "1.0.0"
